spring:
  application:
    name: coursestatistics
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: courseStatistics
  cache:
    cache-names: statisticsCache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=43200s
    type: caffeine
    multi:
      caffeine:
        expireAfterAccess: 300000
      redis:
        defaultExpiration: 600000

server:
  port: 8082 

custom: 
  token: 
    userClaim: userInfo
  question: 
    answer-count: 6
  mq: 
    producer:
      queue-name: 
        courseStatistics: course.statistics.classinteraction
        questionStatistics: course.question.statistics.classinteraction
        questionAnswer: course.question.answer.classinteraction
    consumer:
      queue-name:
        courseStudentAdd: course.student.add.coursestatistics
        answerQuestion: course.question.answer.coursestatistics
        performance: student.performance.studentstatistics
  swagger:
    enable: true
  log: 
    path: E:/logback/${spring.application.name}/${spring.profiles.active}
        