spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 1800
      default-filters:
      - TokenCheck
      - CheckTokenbyUser
      - name: Hystrix
        args:
          name: authHystrixCommand
          fallbackUri: forward:/hystrixTimeout
      routes:
      - id: websocket_sockjs_route
        uri: lb://classinteraction
        predicates:
        - Path=/websocket/course/info**
        filters:
        - StripPrefix= 1
      - id: websocket_route
        uri: lb:ws://classinteraction
        predicates:
        - Path=/websocket/course/**
        filters:
        - StripPrefix= 1
      - id: auth
        uri: lb://userservice
        predicates:
        - Path=${server.servlet.context-path}/auth/**
        filters:
        - StripPrefix= 2
        - name: Hystrix
          args:
            name: authHystrixCommand
            fallbackUri: forward:/hystrixTimeout
        - name: Retry
          args:
            retries: 1
server:
  port: 8888
  http2:
    enabled: true
  servlet:
    context-path: /api
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: false
hystrix:
  command:
    authHystrixCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
app:
  token:
    headerName: accessToken
    userInfoHeader: userInfo
    cache:
      initialCapacity: 500
      maximumSize: 100000
      expireAfterAccessWithMinutes: 30
    ingoreTokenUrls: /api/auth/login, /api/auth/getToken, /websocket/course/, /QUESTIONSREPOSITORY/self/codeSendQuestionPic,/USERSERVICE/back/user/login,/USERSERVICE/back/user/registAccount,/USERSERVICE/back/user/getBackSchools,/PARENTSERVICE/parent/getWxToken/,/PARENTSERVICE/parent/getParentInfo/,/PARENTSERVICE/parent/loginParentService #忽略检查token的URL
    publicKey: EC86@34$123c
    userInfoKey: userInfo
custom:
  log:
    path: E:/logback/${spring.application.name}/${spring.profiles.active}