spring:
  application:
    name: userservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/school
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 127.0.0.1
    port: 5672
server:
  port: 8083

eureka: 
  client:    
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  #instance:
    #ip-address: 114.115.207.28
    #prefer-ip-address: true

com:
  jichuangsi:
    school:
      token:
          jwt:
            secret: EC86@34$123c
            survivalTime: 7200000
          userClaim : userInfo
      swagger:
        enable: true
      mq:
        send_parent_notice: parent.notice.share.classinteraction
      message:
        image:
          domain: http://download.jichuangsi.com/m/i/
          path: d:/code/jichuangsi/download/m/i/
          dateFormat: yyyyMMdd